
    <div class="header-top-desktop__left">
        <?=
            $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header-top-left')
            ->toHtml();

        ?>
    </div>

    <div class="header-top-desktop__midle">
        <?=
            $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header-top-mid')
            ->toHtml();
        ?>
    </div>

 <!-- mobile -->

<div class="header-top-wrap__mobile">
    <div class="header-top-mobile__left">
            <?=
                $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('header-top-left-mobile')
                ->toHtml();
            ?>
    </div>

    <div class="header-top-mobile__right">
            <?=
                $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('header-top-right-mobile')
                ->toHtml();
            ?>
    </div>
</div>

