<div class="footer-showroom__img">
    <?=
        $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('elegence-img-showroom')
        ->toHtml();
    ?>
</div>

<div class="footer-showroom__content">
<?=
    $this->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('footer-showroom')
    ->toHtml();
?>
</div>


<div class="footer-showroom__img">
    <?=
        $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-img-showrrom-weberstore')
        ->toHtml();
    ?>
</div>



